package com.haron.pro.dao.entity;

public class AnniversaryAlbum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anniversary_album.id
     *
     * @mbggenerated Mon Aug 27 15:25:17 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anniversary_album.pic_name
     *
     * @mbggenerated Mon Aug 27 15:25:17 CST 2018
     */
    private String picName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anniversary_album.open_id
     *
     * @mbggenerated Mon Aug 27 15:25:17 CST 2018
     */
    private String openId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anniversary_album.id
     *
     * @return the value of anniversary_album.id
     *
     * @mbggenerated Mon Aug 27 15:25:17 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anniversary_album.id
     *
     * @param id the value for anniversary_album.id
     *
     * @mbggenerated Mon Aug 27 15:25:17 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anniversary_album.pic_name
     *
     * @return the value of anniversary_album.pic_name
     *
     * @mbggenerated Mon Aug 27 15:25:17 CST 2018
     */
    public String getPicName() {
        return picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anniversary_album.pic_name
     *
     * @param picName the value for anniversary_album.pic_name
     *
     * @mbggenerated Mon Aug 27 15:25:17 CST 2018
     */
    public void setPicName(String picName) {
        this.picName = picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anniversary_album.open_id
     *
     * @return the value of anniversary_album.open_id
     *
     * @mbggenerated Mon Aug 27 15:25:17 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anniversary_album.open_id
     *
     * @param openId the value for anniversary_album.open_id
     *
     * @mbggenerated Mon Aug 27 15:25:17 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }
}