package com.haron.pro.dao.entity;

import java.util.Date;

public class ChatPrivate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_private.id
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_private.recieve
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    private String recieve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_private.content
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_private.create_time
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_private.update_time
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_private.id
     *
     * @return the value of chat_private.id
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_private.id
     *
     * @param id the value for chat_private.id
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_private.recieve
     *
     * @return the value of chat_private.recieve
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    public String getRecieve() {
        return recieve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_private.recieve
     *
     * @param recieve the value for chat_private.recieve
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    public void setRecieve(String recieve) {
        this.recieve = recieve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_private.content
     *
     * @return the value of chat_private.content
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_private.content
     *
     * @param content the value for chat_private.content
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_private.create_time
     *
     * @return the value of chat_private.create_time
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_private.create_time
     *
     * @param createTime the value for chat_private.create_time
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_private.update_time
     *
     * @return the value of chat_private.update_time
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_private.update_time
     *
     * @param updateTime the value for chat_private.update_time
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}