package com.haron.pro.dao.mapper;

import com.haron.pro.dao.entity.ChatPrivate;
import com.haron.pro.dao.entity.ChatPrivateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatPrivateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_private
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    int countByExample(ChatPrivateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_private
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    int deleteByExample(ChatPrivateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_private
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_private
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    int insert(ChatPrivate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_private
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    int insertSelective(ChatPrivate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_private
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    List<ChatPrivate> selectByExample(ChatPrivateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_private
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    ChatPrivate selectByPrimaryKey(Integer id);

    ChatPrivate selectByRecieve(String recieve);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_private
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") ChatPrivate record, @Param("example") ChatPrivateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_private
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    int updateByExample(@Param("record") ChatPrivate record, @Param("example") ChatPrivateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_private
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    int updateByPrimaryKeySelective(ChatPrivate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_private
     *
     * @mbggenerated Tue Jul 31 15:38:10 CST 2018
     */
    int updateByPrimaryKey(ChatPrivate record);
}