package com.haron.pro.dao.mapper;

import com.haron.pro.dao.entity.DateRemind;
import com.haron.pro.dao.entity.DateRemindExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DateRemindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_remind
     *
     * @mbggenerated Sun Jul 29 16:08:37 CST 2018
     */
    int countByExample(DateRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_remind
     *
     * @mbggenerated Sun Jul 29 16:08:37 CST 2018
     */
    int deleteByExample(DateRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_remind
     *
     * @mbggenerated Sun Jul 29 16:08:37 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_remind
     *
     * @mbggenerated Sun Jul 29 16:08:37 CST 2018
     */
    int insert(DateRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_remind
     *
     * @mbggenerated Sun Jul 29 16:08:37 CST 2018
     */
    int insertSelective(DateRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_remind
     *
     * @mbggenerated Sun Jul 29 16:08:37 CST 2018
     */
    List<DateRemind> selectByExample(DateRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_remind
     *
     * @mbggenerated Sun Jul 29 16:08:37 CST 2018
     */
    DateRemind selectByPrimaryKey(Integer id);

    List<DateRemind> selectToRemind(String nextRemindDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_remind
     *
     * @mbggenerated Sun Jul 29 16:08:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") DateRemind record, @Param("example") DateRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_remind
     *
     * @mbggenerated Sun Jul 29 16:08:37 CST 2018
     */
    int updateByExample(@Param("record") DateRemind record, @Param("example") DateRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_remind
     *
     * @mbggenerated Sun Jul 29 16:08:37 CST 2018
     */
    int updateByPrimaryKeySelective(DateRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_remind
     *
     * @mbggenerated Sun Jul 29 16:08:37 CST 2018
     */
    int updateByPrimaryKey(DateRemind record);
}