package com.haron.pro.dao.mapper;

import com.haron.pro.dao.entity.OpLog;
import com.haron.pro.dao.entity.OpLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OpLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_log
     *
     * @mbggenerated Thu Aug 09 15:10:42 CST 2018
     */
    int countByExample(OpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_log
     *
     * @mbggenerated Thu Aug 09 15:10:42 CST 2018
     */
    int deleteByExample(OpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_log
     *
     * @mbggenerated Thu Aug 09 15:10:42 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_log
     *
     * @mbggenerated Thu Aug 09 15:10:42 CST 2018
     */
    int insert(OpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_log
     *
     * @mbggenerated Thu Aug 09 15:10:42 CST 2018
     */
    int insertSelective(OpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_log
     *
     * @mbggenerated Thu Aug 09 15:10:42 CST 2018
     */
    List<OpLog> selectByExample(OpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_log
     *
     * @mbggenerated Thu Aug 09 15:10:42 CST 2018
     */
    OpLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_log
     *
     * @mbggenerated Thu Aug 09 15:10:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") OpLog record, @Param("example") OpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_log
     *
     * @mbggenerated Thu Aug 09 15:10:42 CST 2018
     */
    int updateByExample(@Param("record") OpLog record, @Param("example") OpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_log
     *
     * @mbggenerated Thu Aug 09 15:10:42 CST 2018
     */
    int updateByPrimaryKeySelective(OpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table op_log
     *
     * @mbggenerated Thu Aug 09 15:10:42 CST 2018
     */
    int updateByPrimaryKey(OpLog record);
}